name: "starter-oci"
version: "0.1.0"
usage: "Pull, Update and Delete starter charts from an OCI registry"
description: "Pull, Update and Delete starter charts from an OCI registry"
command: "$HELM_PLUGIN_DIR/starter-oci.sh"
