name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version from plugin.yaml
        id: read_version
        run: |
          version=$(grep '^version:' plugin.yaml | awk '{print $2}')
          echo "::set-output name=version::$version"

      - name: Create release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ steps.read_version.outputs.version }}
            release_name: ${{ steps.read_version.outputs.version }}
